### ISSUE TITLE
How do you collect profiles ?

### ISSUE THREAD

**Issue by edouard-lopez** [zeke/electron-developers#2]
Hi, 
I received a spam (unsollicited mail) based on your list of devs for a Electron event. Despite being a JS developer I do not pretend to be skilled in Electron dev. I might have forked a project or two but that's it.

Please remove me from this list as there is real Electron dev that might benefit from the visibility.

**Comment by zeke** [comment]
Sorry to hear you got spammed. To remove yourself, please open a PR.

**Comment by Daandelange** [comment]
I'm kinda in the same situation : I have some activity with Electron but nothing more and got a mail for an Electron event...

Could you please :
 - Explain __how__ you collect data ?
 - Provide an easier way of removing one self ? _I don't want to clone this repo nor do a PR..._

**Comment by Daandelange** [comment]
The __how__ is important because yes my data is public and collectable but no, I'm not (yet?) what you could call an electron developper. Do those who remove themselves by PR risk being automatically re-integrated on the list again ?
And removing oneself should be easy if __you__ collect data, or do our opinions differ on this ?

**Comment by zeke** [comment]
The data is collected using the GitHub API and the libraries.io API.

All of the data is public.

I have created an issue to enable opt-out: https://github.com/zeke/electron-developers/issues/6

I will let you know when that's finished.

**Comment by zeke** [comment]
I shipped an opt-out list in #8.

Sorry for the delay getting that done. I was on parental leave for the last month.
